# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "taskassignment_properties",
    srcs = ["taskassignment.properties"],
)

filegroup(
    name = "taskmanagement_properties",
    srcs = ["taskmanagement.properties"],
)

filegroup(
    name = "modelupdater_properties",
    srcs = ["modelupdater.properties"],
)

filegroup(
    name = "aggregator_properties",
    srcs = ["aggregator.properties"],
)

filegroup(
    name = "collector_properties",
    srcs = ["collector.properties"],
)

filegroup(
    name = "taskscheduler_properties",
    srcs = ["taskscheduler.properties"],
)

filegroup(
    name = "logback_spring",
    srcs = ["logback-spring.xml"],
)

